# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create puppetmaster node
  config.vm.define :puppetmaster do |puppetmaster_config|
      puppetmaster_config.vm.box = "surefoot/centos7-min"   # packed with git@github.com:kenfusion/packer.git
      # puppetmaster_config.vm.box = "ubuntu/trusty64"
      puppetmaster_config.ssh.insert_key = false
      puppetmaster_config.vm.hostname = "puppet.example.com"
      puppetmaster_config.vm.network :private_network, ip: "10.0.15.10"
      puppetmaster_config.vm.provision "shell", inline: "systemctl restart network.service", run: "always" #workaround for bug in vagrant 1.9.1 and el7
      puppetmaster_config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
        vb.linked_clone = true
      end
      puppetmaster_config.vm.provision :shell, path: "bootstrap.sh", privileged: false
  end

  # add some nodes
  # https://docs.vagrantup.com/v2/vagrantfile/tips.html
  (1..4).each do |i|
    config.vm.define "node-0#{i}" do |node|
        node.vm.box = "surefoot/centos7-min"  # packed with git@github.com:kenfusion/packer.git
        node.ssh.insert_key = false
        node.vm.hostname = "node-0#{i}.example.com"
        node.vm.network :private_network, ip: "10.0.15.2#{i}"
        node.vm.provision "shell", inline: "systemctl restart network.service", run: "always" #workaround for bug in vagrant 1.9.1 and el7
        node.vm.network "forwarded_port", guest: 80, host: "800#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "256"
          vb.linked_clone = true
        end
        node.vm.provision :shell, path: "bootstrap.sh", privileged: false
    end
  end

end
