---
- name: include vars
  include_vars: vars.yml

- name: include vault_vars
  include_vars: vault.yml

- name: install mysql repo on el 7 based OS
  yum:
    name: "http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm"
    state: present
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: install mysql
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
   - mysql-server
   - MySQL-python
- name: configure mysql
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mysqld
- name: start mysqld
  service:
    name: "{{ mysql_service }}"
    state: started
- name: create db
  mysql_db:
    name: "{{ db_name }}"
    state: present
- name: create db user
  mysql_user:
    name: "{{ vault_db_user }}"
    password: "{{ vault_db_password }}"
    priv: "*.*:ALL"
    host: "%"
    state: present
